[package]
name = "crypto_pals"
version = "0.1.0"
authors = ["Neel Kuila <neelk1123@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.9.0"
hex = "0.3.1"
rand = "0.4.5"
real_mt = {version="1.1.1", package="mersenne_twister"}

